SELECT
  ol.icustay_id,
  ROUND( (CAST(EXTRACT(epoch FROM ol.charttime-og.intime)/(60*60) AS numeric)), 2) AS charthour,
  ol.po2,
  ol.pco2,
  ol.arterialph,
  ol.potassium,
  ol.calcium,
  ol.sodium,
  ol.chloride,
  ol.glucose,
  ol.bicarbonate,
  ol.be,
  ol.arterialwbc,
  ol.arterialrbc,
  ol.plt,
  ol.crp,
  ol.lactate,
  ol.alt,
  ol.ast,
  ol.creatinine,
  ol.bun,
  ol.amylase,
  ol.lipase,
  ol.urine_ph,
  ol.urine_wbc,
  ol.urine_protein,
  ol.urine_glucose,
  ol.urine_bilirubin,
  ol.urine_ketone,
  ol.urine_rbc,
  ol.specificgravity,
  ol.urobilinogen,
  ol.urine_blood,
  ol.urine_color,
  ol.aptt,
  ol.pt,
  ol.inr,
  ol.d_dimer,
  ol.fib
FROM oliguria og
  LEFT JOIN oliguria_labevents ol
    ON og.icustay_id = ol.icustay_id
       AND ol.charttime BETWEEN og.intime-INTERVAL '6' HOUR AND og.intime+ INTERVAL '1' DAY
